[archive]
build_output_dir = 'Source\Built'
archive_location = '\\nirvana\Measurements\VeriStandAddons\routing_and_faulting_custom_device'

[dependencies.niveristand-routing-and-faulting-message-library]
libraries = ['CDMessaging.lvlibp', 'SLSCSwitchMessaging.lvlibp', 'NISWITCHMessaging.lvlibp']
copy_location = 'Includes'

[projects.raf]
path = 'Source\Routing and Faulting\Routing and Faulting Custom Device.lvproj'

[projects.slsc]
path = 'Source\SLSC Switch\SLSC Switch Custom Device.lvproj'

[projects.ni_switch]
path = 'Source\NI-SWITCH\NI-SWITCH Custom Device.lvproj'

[projects.examples]
path = 'Source\Scripting Examples\Scripting Examples.lvproj'

[[build.steps]]
name = 'Routing and Faulting Configuration Library'
type = 'lvBuildSpec'
project = '{raf}'
target = 'My Computer'
build_spec = 'Configuration Release'
dependency_target = 'Windows'

[[build.steps]]
name = 'Routing and Faulting Windows Engine Library'
type = 'lvBuildSpec'
project = '{raf}'
target = 'My Computer'
build_spec = 'Engine Release'
dependency_target = 'Windows'

[[build.steps]]
name = 'Routing and Faulting Pharlap Engine Library'
type = 'lvBuildSpec'
project = '{raf}'
target = 'RT PXI Target'
build_spec = 'Engine Release'
dependency_target = 'Pharlap'

[[build.steps]]
name = 'Routing and Faulting Linux x64 Engine Library'
type = 'lvBuildSpec'
project = '{raf}'
target = 'RT CompactRIO Target - Linux x64'
build_spec = 'Engine Release'
dependency_target = 'Linux_x64'

[[build.steps]]
name = 'Routing and Faulting Linux x86 Engine Library'
type = 'lvBuildSpec'
project = '{raf}'
target = 'RT CompactRIO Target - Linux ARM'
build_spec = 'Engine Release'
dependency_target = 'Linux_32_ARM'

[[build.steps]]
name = 'Routing and Faulting Scripting API'
type = 'lvBuildSpec'
project = '{raf}'
target = 'My Computer'
build_spec = 'Scripting API'
dependency_target = 'Windows'

[[build.steps]]
name = 'SLSC Switch Configuration Library'
type = 'lvBuildSpec'
project = '{slsc}'
target = 'My Computer'
build_spec = 'Configuration Release'
dependency_target = 'Windows'

[[build.steps]]
name = 'SLSC Switch Windows Engine Library'
type = 'lvBuildSpec'
project = '{slsc}'
target = 'My Computer'
build_spec = 'Engine Release'
dependency_target = 'Windows'

[[build.steps]]
name = 'SLSC Switch Pharlap Engine Library'
type = 'lvBuildSpec'
project = '{slsc}'
target = 'RT PXI Target'
build_spec = 'Engine Release'
dependency_target = 'Pharlap'

[[build.steps]]
name = 'SLSC Switch Linux x64 Engine Library'
type = 'lvBuildSpec'
project = '{slsc}'
target = 'RT CompactRIO Target - Linux x64'
build_spec = 'Engine Release'
dependency_target = 'Linux_x64'

[[build.steps]]
name = 'SLSC Switch Linux x86 Engine Library'
type = 'lvBuildSpec'
project = '{slsc}'
target = 'RT CompactRIO Target - Linux ARM'
build_spec = 'Engine Release'
dependency_target = 'Linux_32_ARM'

[[build.steps]]
name = 'SLSC Switch Scripting API'
type = 'lvBuildSpec'
project = '{slsc}'
target = 'My Computer'
build_spec = 'Scripting API'
dependency_target = 'Windows'

[[build.steps]]
name = 'NI-SWITCH Configuration Library'
type = 'lvBuildSpec'
project = '{ni_switch}'
target = 'My Computer'
build_spec = 'Configuration Release'
dependency_target = 'Windows'

[[build.steps]]
name = 'NI-SWITCH Windows Engine Library'
type = 'lvBuildSpec'
project = '{ni_switch}'
target = 'My Computer'
build_spec = 'Engine Release'
dependency_target = 'Windows'

[[build.steps]]
name = 'NI-SWITCH Pharlap Engine Library'
type = 'lvBuildSpec'
project = '{ni_switch}'
target = 'RT PXI Target'
build_spec = 'Engine Release'
dependency_target = 'Pharlap'

[[build.steps]]
name = 'NI-SWITCH Linux x64 Engine Library'
type = 'lvBuildSpec'
project = '{ni_switch}'
target = 'RT CompactRIO Target - Linux x64'
build_spec = 'Engine Release'
dependency_target = 'Linux_x64'

[[build.steps]]
name = 'Examples'
type = 'lvBuildSpec'
project = '{examples}'
target = 'My Computer'
build_spec = 'Examples'
dependency_target = 'Windows'

[[package]]
type = 'nipkg'
control_file = 'control_routing_faulting'
package_output_dir = 'Source\Built'

[package.payload_map]
'Source\\Built\\Routing and Faulting' = 'documents\National Instruments\NI VeriStand {veristand_version}\Custom Devices\Routing and Faulting'
'Source\\Built\\Errors\\Routing and Faulting' = 'ni-paths-NISHAREDDIR\LabVIEW Run-Time\{veristand_version}\errors\English'

[[package]]
type = 'nipkg'
control_file = 'control_routing_faulting_scripting'
package_output_dir = 'Source\Built'

[package.payload_map]
'Source\\Built\\Scripting\\Routing and Faulting' = 'ni-paths-LV{veristand_version}DIR\vi.lib\addons\VeriStand Custom Device Scripting APIs\Routing and Faulting'
'Source\\Built\\Errors\\Routing and Faulting' = 'ni-paths-LV{veristand_version}DIR\resource\errors\English'

[[package]]
type = 'nipkg'
control_file = 'control_slsc_switch'
package_output_dir = 'Source\Built'

[package.payload_map]
'Source\\Built\\SLSC Switch' = 'documents\National Instruments\NI VeriStand {veristand_version}\SLSC Plugins\Modules\SLSC Switch'
'Source\\Built\\Errors\\SLSC Switch' = 'ni-paths-LV{veristand_version}DIR\resource\errors\English'

[[package]]
type = 'nipkg'
control_file = 'control_slsc_switch_scripting'
package_output_dir = 'Source\Built'

[package.payload_map]
'Source\\Built\\Scripting\\SLSC Switch' = 'ni-paths-LV{veristand_version}DIR\vi.lib\addons\VeriStand Custom Device Scripting APIs\SLSC Switch'
'Source\\Built\\Errors\\SLSC Switch' = 'ni-paths-LV{veristand_version}DIR\resource\errors\English'

[[package]]
type = 'nipkg'
control_file = 'control_ni_switch'
package_output_dir = 'Source\Built'

[package.payload_map]
'Source\\Built\\NI-SWITCH' = 'documents\National Instruments\NI VeriStand {veristand_version}\Custom Devices\NI-SWITCH'
'Source\\Built\\Errors\\NI-SWITCH' = 'ni-paths-NISHAREDDIR\LabVIEW Run-Time\{veristand_version}\errors\English'

[[package]]
type = 'nipkg'
payload_dir = 'Source\Built\Scripting Examples'
install_destination = 'ni-paths-LV{veristand_version}DIR\examples\NI VeriStand Custom Devices\Routing and Faulting'
control_file = 'control_examples'
package_output_dir = 'Source\Built'

[[package]]
type = 'nipkg'
payload_dir = 'Source\Shared\Custom Device LabVIEW Common'
install_destination = 'ni-paths-LV{veristand_version}DIR'
control_file = 'control_custom_device_labview_support_common'
package_output_dir = 'Source\Built'

[notification]
type = 'teams'
